spring:
  profiles:
    # 目前啟用執行環境的設定檔
    # 如果是用 MySQL，請改成 "prod"
    # 如果是用 H2 記憶體資料庫，請設為 "dev"
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm   # JSON 時間格式設定
    time-zone: GMT+8                # 時區設定（GMT+8 為台灣時間）