spring:
  # 資料庫連線設定（這裡用的是 MySQL）
  datasource:
    # 指定要用的 JDBC 驅動程式（MySQL 的驅動）
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 連線資料庫的網址：連到本機的 dinner 資料庫
    # serverTimezone=Asia/Taipei：設定時區（避免時間錯誤）
    # characterEncoding=utf-8：設定字元編碼為 UTF-8（避免亂碼）
    url: jdbc:mysql://localhost:3306/dinner?serverTimezone=Asia/Taipei&characterEncoding=utf-8

   
    username: root      # 資料庫使用者名稱
    password: 12345678  # 資料庫密碼

  # SQL 初始化腳本設定
  sql:
    init:
      mode: never       # never = 啟動時不會自動執行 schema.sql 或 data.sql
      encoding: UTF-8   # 若有執行腳本，指定它的編碼格式（預防亂碼）

# Spring Security 權限控制的自定義開關（需搭配程式碼撰寫支援）
security:
  # false = 啟用權限驗證，API 會檢查使用者是否登入或有權限
  # 若設為 true，所有 API 都可以不登入直接使用
  permit-all: false