-- 餐廳資料
CREATE TABLE IF NOT EXISTS restaurants (
    restaurant_id    INT GENERATED BY DEFAULT AS IDENTITY (START WITH 51) PRIMARY KEY,  -- 餐廳編號
    restaurant_name  VARCHAR(64)  NOT NULL,                                             -- 餐廳名稱
    category         VARCHAR(32)  NOT NULL,                                             -- 餐廳分類
    image_url        VARCHAR(256),                                                      -- 餐廳圖片URL
    visited_count    INT DEFAULT 0,                                                     -- 選擇次數
    last_selected_at TIMESTAMP NULL DEFAULT NULL,                                       -- 最後選擇時間
    updated_at       TIMESTAMP NULL DEFAULT NULL,                                       -- 最後更新資料時間
    note             VARCHAR(512)                                                       -- 備註
);

-- 餐點資料
CREATE TABLE IF NOT EXISTS dishes (
    dish_id       INT AUTO_INCREMENT PRIMARY KEY,  -- 餐點編號
    restaurant_id INT NOT NULL,                    -- 餐點對應餐廳編號
    price         INT NOT NULL,                    -- 餐點價格
    dish_name     VARCHAR(32) NOT NULL             -- 餐點名稱
);

-- 帳號資料
CREATE TABLE IF NOT EXISTS users
(
    user_id            INT GENERATED BY DEFAULT AS IDENTITY (START WITH 30) PRIMARY KEY,  -- 使用者 ID
    username           VARCHAR(256) NOT NULL UNIQUE,                                      -- 使用者帳號
    user_password      VARCHAR(256) NOT NULL,                                             -- 使用者密碼
    roles              VARCHAR(32),                                                       -- 使用者角色
    created_date       TIMESTAMP NOT NULL,                                                -- 建立時間
    last_modified_date TIMESTAMP NOT NULL                                                 -- 最後修改時間
);

-- 訂單主表：紀錄每一筆訂單的整體資訊
CREATE TABLE orders
(
    order_id           INT       NOT NULL PRIMARY KEY AUTO_INCREMENT, -- 訂單編號
    user_id            INT       NOT NULL,                            -- 下訂單的用戶ID
    total_amount       INT       NOT NULL,                            -- 訂單總金額
    created_date       TIMESTAMP NOT NULL,                            -- 訂單建立時間
    last_modified_date TIMESTAMP NOT NULL                             -- 訂單最後修改時間
);

-- 訂單項目明細表：記錄每張訂單中所包含的餐點明細
CREATE TABLE order_item
(
    order_item_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, -- 訂單項目編號
    order_id      INT NOT NULL,                            -- 對應的訂單編號
    dish_id       INT NOT NULL,                            -- 餐點ID
    quantity      INT NOT NULL,                            -- 該餐點的購買數量
    amount        INT NOT NULL                             -- 該餐點的總金額
);
