-- Restaurant
CREATE TABLE IF NOT EXISTS restaurants (
    restaurant_id    INT GENERATED BY DEFAULT AS IDENTITY (START WITH 51) PRIMARY KEY,     -- 餐廳編號，自動遞增
    restaurant_name  VARCHAR(64)  NOT NULL,              -- 餐廳名稱，不可為空
    category         VARCHAR(32)  NOT NULL,              -- 餐廳類別（如主餐、輕食等），不可為空
    image_url        VARCHAR(256),                       -- 餐廳圖片網址，允許為空
    visited_count    INT DEFAULT 0,                      -- 拜訪次數，預設為 0
    last_selected_at         TIMESTAMP NULL DEFAULT NULL,        -- 最後選擇時間，預設為 NULL
    updated_at       TIMESTAMP NULL DEFAULT NULL,        -- 最後更新時間，預設為 NULL
    note             VARCHAR(512)                        -- 備註欄位，可為空
);

-- User
CREATE TABLE IF NOT EXISTS users
(
    user_id            INT GENERATED BY DEFAULT AS IDENTITY (START WITH 30) PRIMARY KEY,  -- 使用者 ID，自動遞增
    username           VARCHAR(256) NOT NULL UNIQUE,                                      -- 使用者帳號（唯一，不可為空）
    user_password      VARCHAR(256) NOT NULL,                                             -- 使用者密碼（不可為空）
    roles              VARCHAR(32),                                                       -- 使用者角色（如 admin, user 等），可為空
    created_date       TIMESTAMP NOT NULL,                                                -- 建立時間
    last_modified_date TIMESTAMP NOT NULL                                                 -- 最後修改時間
);